version: "3.9"
services:
  # vscode will connect to this service as the dev container
  cproject:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - base_tag=bookworm
        - llvm_version=16
    volumes:
      - ../..:/workspaces
    command: sleep infinity
    env_file:
      # If you need to access the WORKSPACE_* envars in the container
      - resources/.env
