version: "3.9"
services:
  # vscode will connect to this service as the dev container
  example-devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${WORKSPACE_SOURCE:?}:${WORKSPACE_TARGET:?}
    command: sleep infinity
    depends_on:
      - example-service
    env_file:
      # If you need to access the WORKSPACE_* envars in the container
      - .env

  # Another container with access to the workspace files.
  # It serves the workspace files - http://example-service:8000
  example-service:
    image: python
    working_dir: ${WORKSPACE_ROOT:?}
    command: python -m http.server
    volumes:
      - ${WORKSPACE_SOURCE:?}:${WORKSPACE_TARGET:?}

volumes:
  # $WORKSPACE_SOURCE is "devcontainer-volume" when the workspace is in a volume
  devcontainer-volume:
    name: ${WORKSPACE_CONTAINER_VOLUME_SOURCE}
    external: true
