version: "3.9"
services:
  c-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - base_tag=alpine
    volumes:
      - ../..:/workspaces
    command: sleep infinity
    env_file:
      # If you need to access the WORKSPACE_* envars in the container
      - resources/.env
