name: Docker image

on:
  pull_request:
    branches: [ "minishell" ]
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd .devcontainer; touch ./resources/.env && docker compose up -d
